export const HomeGalleryData = [
  {
    id: 1,
    slug: "sailboat",
    title: "Sailboat",
    image: "/assets/images/home/1.jpg",
    description: "he",
    price: 30,
    discount: 15,
    artist: "John Doe",
    quantity: 1,
    userEmail: "19303063@iubat.edu",
  },
  {
    id: 2,
    slug: "captivemind",
    title: "Captive Mind",
    image: "/assets/images/home/2.jpg",
    description: "he",
    price: 30,
    discount: 15,
    artist: "John Doe",
    quantity: 1,
    userEmail: "19303062@iubat.edu",
  },
  {
    id: 3,
    slug: "apath",
    title: "A path",
    image: "/assets/images/home/3.jpg",
    description: "he",
    price: 30,
    discount: 15,
    artist: "John Doe",
    quantity: 1,
    userEmail: "19303062@iubat.edu",
  },
  {
    id: 4,
    slug: "beautifullpath",
    title: "Beautifull path",
    image: "/assets/images/home/4.jpg",
    description: "he",
    price: 30,
    discount: 15,
    artist: "John Doe",
    quantity: 1,
    userEmail: "19303062@iubat.edu",
  },
  {
    id: 5,
    slug: "watercolor",
    title: "Water Color",
    image: "/assets/images/home/5.jpg",
    description: "he",
    price: 30,
    discount: 15,
    artist: "John Doe",
    quantity: 1,
    userEmail: "19303062@iubat.edu",
  },
  {
    id: 6,
    slug: "seabeach",
    title: "Sea Beach",
    image: "/assets/images/home/6.jpg",
    description: "he",
    price: 30,
    discount: 15,
    artist: "John Doe",
    quantity: 1,
    userEmail: "19303062@iubat.edu",
  },
  {
    id: 7,
    slug: "seaside",
    title: "Sea Side",
    image: "/assets/images/home/7.jpg",
    description: "he",
    price: 30,
    discount: 15,
    artist: "John Doe",
    quantity: 1,
    userEmail: "19303062@iubat.edu",
  },
  {
    id: 8,
    slug: "boat",
    title: "Boat",
    image: "/assets/images/home/8.jpg",
    description: "he",
    price: 30,
    discount: 15,
    artist: "John Doe",
    quantity: 1,
    userEmail: "19303062@iubat.edu",
  },
];
