export const HomeGalleryData = [
  {
    id: 1,
    slug: "sailboat",
    title: "Sailboat",
    img: "/assets/images/home/1.jpg",
    price: "৳15.00",
    discount: "৳30.00",
    author: "John Doe",
  },
  {
    id: 2,
    slug: "Captive Mind",
    title: "Captive Mind",
    img: "/assets/images/home/2.jpg",
    price: "৳15.00",
    discount: "৳30.00",
    author: "John Doe",
  },
  {
    id: 3,
    slug: "A path",
    title: "A path",
    img: "/assets/images/home/3.jpg",
    price: "৳15.00",
    discount: "৳30.00",
    author: "John Doe",
  },
  {
    id: 4,
    slug: "Beautifull path",
    title: "Beautifull path",
    img: "/assets/images/home/4.jpg",
    price: "৳15.00",
    discount: "৳30.00",
    author: "John Doe",
  },
  {
    id: 5,
    slug: "Water Color",
    title: "Water Color",
    img: "/assets/images/home/5.jpg",
    price: "৳15.00",
    discount: "৳30.00",
    author: "John Doe",
  },
  {
    id: 6,
    slug: "Sea Beach",
    title: "Sea Beach",
    img: "/assets/images/home/6.jpg",
    price: "৳15.00",
    discount: "৳30.00",
    author: "John Doe",
  },
  {
    id: 7,
    slug: "Sea Side",
    title: "Sea Side",
    img: "/assets/images/home/7.jpg",
    price: "৳15.00",
    discount: "৳30.00",
    author: "John Doe",
  },
  {
    id: 8,
    slug: "Boat",
    title: "Boat",
    img: "/assets/images/home/8.jpg",
    price: "৳15.00",
    discount: "৳30.00",
    author: "John Doe",
  },
];
